namespace FunctionalCore;

/// <summary>
/// Extension methods for Result<E, T>
/// Result<E, T>用の拡張メソッド
/// </summary>
public static class ResultExtensions
{
    /// <summary>
    /// Returns the value if successful, otherwise throws an exception generated by the provided factory
    /// 成功時は値を返し、失敗時は指定の例外ファクトリで例外を投げる
    /// </summary>
    /// <param name="result"></param>
    /// <param name="toException"></param>
    /// <returns></returns>
    public static T ValueOrThrow<E, T>(this Result<E, T> result, Func<E, Exception> toException)
    {
        ArgumentNullException.ThrowIfNull(toException);

        if (result.IsSuccess)
        {
            return result.Value;
        }

        var ex = toException(result.Error);

        if (ex == null)
        {
            throw new InvalidOperationException("Exception factory returned null");
        }

        throw ex;
    }

    #region Collections / コレクション

    /// <summary>
    /// Converts a sequence of Result into a Result of sequence
    /// Resultのシーケンスを一つのResultにまとめる
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <param name="results"></param>
    /// <returns></returns>
    public static Result<E, IEnumerable<T>> Sequence<E, T>(this IEnumerable<Result<E, T>> results)
    {
        ArgumentNullException.ThrowIfNull(results);

        var lst = new List<T>();
        foreach (var r in results)
        {
            if (r.IsSuccess == false)
            {
                return Result<E, IEnumerable<T>>.Fail(r.Error);
            }
            lst.Add(r.Value);
        }

        return Result<E, IEnumerable<T>>.Ok(lst);
    }

    /// <summary>
    /// Applies a function to a sequence and combines the results into one Result
    /// シーケンスに関数を適用してResultにまとめる
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <typeparam name="U"></typeparam>
    /// <param name="items"></param>
    /// <param name="selector"></param>
    /// <returns></returns>
    public static Result<E, IEnumerable<U>> Traverse<E, T, U>(this IEnumerable<T> items, Func<T, Result<E, U>> selector)
    {
        ArgumentNullException.ThrowIfNull(items);
        ArgumentNullException.ThrowIfNull(selector);

        var lst = new List<U>();
        foreach (var item in items)
        {
            var r = selector(item);
            if (r.IsSuccess == false)
            {
                return Result<E, IEnumerable<U>>.Fail(r.Error);
            }
            lst.Add(r.Value);
        }

        return Result<E, IEnumerable<U>>.Ok(lst);
    }

    #endregion

    #region Conversions

    /// <summary>
    /// Converts Option<T> to Result<E, T>
    /// Option<T>をResult<E, T>に変換する
    /// </summary>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <param name="option"></param>
    /// <param name="errorIfNone"></param>
    /// <returns></returns>
    public static Result<E, T> ToResultFromOption<E, T>(this Option<T> option, E error)
    {
        return option.ToResultFromOption(() => error);
    }

    /// <summary>
    /// 
    /// </summary>
    /// <typeparam name="E"></typeparam>
    /// <typeparam name="T"></typeparam>
    /// <param name="option"></param>
    /// <param name="errorFactory"></param>
    /// <returns></returns>
    public static Result<E, T> ToResultFromOption<E, T>(this Option<T> option, Func<E> errorFactory)
    {
        ArgumentNullException.ThrowIfNull(errorFactory);

        return option.Match(x => Result<E, T>.Ok(x),
                            () => Result<E, T>.Fail(errorFactory()));
    }

    /// <summary>
    /// Converts a value to Result<E, T>, returning failure if null
    /// 任意の値をResult<E, T>に変換する。nullなら失敗させる
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <param name="value"></param>
    /// <param name="errorIfNull"></param>
    /// <returns></returns>
    public static Result<E, T> ToResult<E, T>(this T value, E errorIfNull)
    {
        if (value is null)
        {
            return Result<E, T>.Fail(errorIfNull);
        }

        return  Result<E, T>.Ok(value);
    }
    #endregion
}