namespace FunctionalCore.Extensions;

/// <summary>
/// Extension methods for Result<E, T>
/// Result<E, T>用の拡張メソッド
/// </summary>
public static class ResultExtensions
{
    /// <summary>
    /// Executes side-effect regardless of state.
    /// 状態に関係なく副作用を実行する。
    ///
    /// Does not change the Option.
    /// 状態は変更しない
    /// </summary>
    public static Result<E, T> TapBoth<E, T>(this Result<E, T> result, Action<T> onSuccess, Action<E> onFailure)
    {
        result.ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(onSuccess);
        ArgumentNullException.ThrowIfNull(onFailure);

        if (result.IsSuccess)
            onSuccess(result.Value);
        else
            onFailure(result.Error);

        return result;
    }

    #region Value Extraction / 値の取り出し
    /// <summary>
    /// Returns the value if successful, otherwise throws an exception generated by the provided factory
    /// 成功時は値を返し、失敗時は指定の例外ファクトリで例外を投げる。
    /// </summary>
    /// <param name="result"></param>
    /// <param name="toException"></param>
    /// <returns></returns>
    public static T ValueOrThrow<E, T>(this Result<E, T> result, Func<E, Exception> toException)
    {
        result.ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(toException);

        if (result.IsSuccess)
        {
            return result.Value;
        }

        var ex = toException(result.Error);

        if (ex == null)
        {
            throw new InvalidOperationException("Exception factory returned null");
        }

        throw ex;
    }

    /// <summary>
    /// Returns the value if it is successful; otherwise returns the specified fallback value.
    /// 成功した場合はその値を返し、失敗した場合は指定した代替値を返す。
    /// </summary>
    /// <param name="defaultValue">
    /// The value to return if the result is a failure.
    /// 失敗した場合に返す代替値。
    /// </param>
    /// <returns>
    /// The contained value if it is successful; otherwise the specified fallback value.
    /// 成功した場合はその値、失敗した場合は指定した代替値。
    /// </returns>
    public static T GetValueOr<E, T>(this Result<E, T> result, T defaultValue)
    {
        result.ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(defaultValue);

        return result.IsSuccess ? result.Value : defaultValue;
    }

    /// <summary>
    /// Returns this result if it is successful; otherwise returns the specified alternative result.
    /// 成功した場合はこの Result を返し、失敗した場合には指定した代替 Result を返す。
    /// </summary>
    /// <param name="other">
    /// The alternative result to return if this result is fail.
    /// 失敗した場合に返す代替の Result。
    /// </param>
    /// <returns>
    /// This result if it is successful; otherwise the specified alternative result.
    /// 成功した場合はこの Result、それ以外は代替 Result。
    /// </returns>
    public static Result<E, T> Or<E, T>(this Result<E, T> result, Result<E, T> other)
    {
        result.ThrowIfNotInitialized();

        return result.IsSuccess ? result : other;
    }

    /// <summary>
    /// Returns this result if it is successful; otherwise returns a result produced by the specified factory.
    /// 成功した場合はこの Result を返し、失敗した場合は指定した関数で生成された Result を返す。
    /// </summary>
    /// <param name="otherFactory">
    /// A function that produces an alternative result if no value is present.
    /// 失敗した場合に代替 Result を生成する関数。
    /// </param>
    /// <returns>
    /// This result if it is successful; otherwise the result produced by the factory.
    /// 成功した場合はこの Result、それ以外は生成された Result。
    /// </returns>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="otherFactory"/> is null.
    /// <paramref name="otherFactory"/> が null の場合にスローされる。
    /// </exception>
    public static Result<E, T> Or<E, T>(this Result<E, T> result, Func<Result<E, T>> otherFactory)
    {
        result.ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(otherFactory);

        return result.IsSuccess ? result : otherFactory();
    }
    #endregion

    #region Conversions / 変換
    /// <summary>
    /// Converts Option<T> to Result<E, T>
    /// Option<T>をResult<E, T>に変換する。
    /// </summary>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <param name="option"></param>
    /// <param name="errorIfNone"></param>
    /// <returns></returns>
    public static Result<E, T> ToResult<E, T>(this Option<T> option, E error)
    {
        return option.ToResult(() => error);
    }

    /// <summary>
    /// 
    /// </summary>
    /// <typeparam name="E"></typeparam>
    /// <typeparam name="T"></typeparam>
    /// <param name="option"></param>
    /// <param name="errorFactory"></param>
    /// <returns></returns>
    public static Result<E, T> ToResult<E, T>(this Option<T> option, Func<E> errorFactory)
    {
        ArgumentNullException.ThrowIfNull(errorFactory);

        return option.Match(x => Result<E, T>.Ok(x),
                            () => Result<E, T>.Fail(errorFactory()));
    }

    /// <summary>
    /// Converts a value to Result<E, T>, returning failure if null
    /// 任意の値をResult<E, T>に変換する。nullなら失敗させる。
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <param name="value"></param>
    /// <param name="errorIfNull"></param>
    /// <returns></returns>
    public static Result<E, T> ToResult<E, T>(this T value, E errorIfNull)
    {
        if (value is null)
        {
            return Result<E, T>.Fail(errorIfNull);
        }

        return Result<E, T>.Ok(value);
    }
    #endregion
    #region Collections / コレクション

    /// <summary>
    /// Converts a sequence of Result into a Result of sequence
    /// Resultのシーケンスを一つのResultにまとめる。
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <param name="results"></param>
    /// <returns></returns>
    public static Result<E, IReadOnlyCollection<T>> Sequence<E, T>(this IEnumerable<Result<E, T>> results)
    {
        //ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(results);

        var lst = new List<T>();
        foreach (var r in results)
        {
            if (r.IsSuccess == false)
            {
                return Result<E, IReadOnlyCollection<T>>.Fail(r.Error);
            }
            lst.Add(r.Value);
        }

        return Result<E, IReadOnlyCollection<T>>.Ok(lst);
    }

    /// <summary>
    /// Applies a function to a sequence and combines the results into one Result
    /// シーケンスに関数を適用してResultにまとめる。
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <typeparam name="U"></typeparam>
    /// <param name="items"></param>
    /// <param name="selector"></param>
    /// <returns></returns>
    public static Result<E, IReadOnlyCollection<U>> Traverse<E, T, U>(this IEnumerable<T> items, Func<T, Result<E, U>> selector)
    {
        ArgumentNullException.ThrowIfNull(items);
        ArgumentNullException.ThrowIfNull(selector);

        var lst = new List<U>();
        foreach (var item in items)
        {
            var r = selector(item);
            if (r.IsSuccess == false)
            {
                return Result<E, IReadOnlyCollection<U>>.Fail(r.Error);
            }
            lst.Add(r.Value);
        }

        return Result<E, IReadOnlyCollection<U>>.Ok(lst);
    }
    #endregion
}