namespace FunctionalCore.Extensions;

/// <summary>
/// Provides extension methods for Result<E, T>.
/// <para>Result<E, T>に対する拡張メソッドを提供する。</para>
/// </summary>
public static class ResultExtensions
{
    /// <summary>
    /// Executes side-effect regardless of state.
    /// <para>状態に関係なく副作用を実行する。</para>
    ///
    /// Does not change the Result.
    /// <para>状態は変更しない</para>
    /// </summary>
    public static Result<E, T> TapBoth<E, T>(this Result<E, T> result, Action<T> onSuccess, Action<E> onFailure)
    {
        result.ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(onSuccess);
        ArgumentNullException.ThrowIfNull(onFailure);

        if (result.IsSuccess)
            onSuccess(result.Value);
        else
            onFailure(result.Error);

        return result;
    }

    #region Value Extraction / 値の取り出し
    /// <summary>
    /// Returns the value if successful, otherwise throws an exception generated by the provided factory
    /// <para>成功時は値を返し、失敗時は指定の例外ファクトリで例外を投げる。</para>
    /// </summary>
    /// <param name="result"></param>
    /// <param name="toException"></param>
    /// <returns></returns>
    public static T ValueOrThrow<E, T>(this Result<E, T> result, Func<E, Exception> toException)
    {
        result.ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(toException);

        if (result.IsSuccess)
            return result.Value;

        var ex = toException(result.Error);

        if (ex is null)
            throw new InvalidOperationException("Exception factory must not return null.");

        throw ex;
    }

    /// <summary>
    /// Returns the value if it is successful; otherwise returns the specified fallback value.
    /// <para>成功した場合はその値を返し、失敗した場合は指定した代替値を返す。</para>
    /// </summary>
    /// <param name="defaultValue">
    /// The value to return if the result is a failure.
    /// <para>失敗した場合に返す代替値。</para>
    /// </param>
    /// <returns>
    /// The contained value if it is successful; otherwise the specified fallback value.
    /// <para>成功した場合はその値、失敗した場合は指定した代替値。</para>
    /// </returns>
    public static T GetValueOr<E, T>(this Result<E, T> result, T defaultValue)
    {
        result.ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(defaultValue);

        return result.IsSuccess ? result.Value : defaultValue;
    }

    /// <summary>
    /// Returns this result if it is successful; otherwise returns the specified alternative result.
    /// <para>成功した場合はこの Result を返し、失敗した場合には指定した代替 Result を返す。</para>
    /// </summary>
    /// <param name="other">
    /// The alternative result to return if this result is fail.
    /// <para>失敗した場合に返す代替の Result。</para>
    /// </param>
    /// <returns>
    /// This result if it is successful; otherwise the specified alternative result.
    /// <para>成功した場合はこの Result、それ以外は代替 Result。</para>
    /// </returns>
    public static Result<E, T> Or<E, T>(this Result<E, T> result, Result<E, T> other)
    {
        if (result.IsSuccess)
            return result;
        
        other.ThrowIfNotInitialized();

        return other;
    }

    /// <summary>
    /// Returns this result if it is successful; otherwise returns a result produced by the specified factory.
    /// <para>成功した場合はこの Result を返し、失敗した場合は指定した関数で生成された Result を返す。</para>
    /// </summary>
    /// <param name="otherFactory">
    /// A function that produces an alternative result if no value is present.
    /// <para>失敗した場合に代替 Result を生成する関数。</para>
    /// </param>
    /// <returns>
    /// This result if it is successful; otherwise the result produced by the factory.
    /// <para>成功した場合はこの Result、それ以外は生成された Result。</para>
    /// </returns>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="otherFactory"/> is null.
    /// <paramref name="otherFactory"/> が null の場合にスローされる。
    /// </exception>
    public static Result<E, T> Or<E, T>(this Result<E, T> result, Func<Result<E, T>> otherFactory)
    {
        result.ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(otherFactory);

        if (result.IsSuccess)
            return result;

        var other = otherFactory();
        other.ThrowIfNotInitialized();

        return other;
    }
    #endregion

    #region Conversions / 変換
    /// <summary>
    /// Converts Option<T> to Result<E, T>
    /// <para>Option<T>をResult<E, T>に変換する。</para>
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <param name="option"></param>
    /// <param name="error"></param>
    /// <returns></returns>
    public static Result<E, T> ToResult<E, T>(this Option<T> option, E error)
    {
        return option.ToResult(() => error);
    }

    /// <summary>
    /// Converts Option<T> to Result<E, T>
    /// <para>Option<T>をResult<E, T>に変換する。</para>
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <param name="option"></param>
    /// <param name="errorFactory"></param>
    /// <returns></returns>
    public static Result<E, T> ToResult<E, T>(this Option<T> option, Func<E> errorFactory)
    {
        ArgumentNullException.ThrowIfNull(errorFactory);

        return option.Match(x => Result<E, T>.Ok(x),
                            () => Result<E, T>.Fail(errorFactory()));
    }

    /// <summary>
    /// Converts a value to Result<E, T>, returning failure if null
    /// <para>任意の値をResult<E, T>に変換する。nullなら失敗させる。</para>
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <param name="value"></param>
    /// <param name="errorIfNull"></param>
    /// <returns></returns>
    public static Result<E, T> ToResult<E, T>(this T value, E errorIfNull)
    {
        if (value is null)
            return Result<E, T>.Fail(errorIfNull);

        return Result<E, T>.Ok(value);
    }
    #endregion

    #region Collections / コレクション

    /// <summary>
    /// Converts a sequence of Result into a Result of sequence
    /// <para>Resultのシーケンスを一つのResultにまとめる。</para>
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <param name="results"></param>
    /// <returns></returns>
    public static Result<E, IReadOnlyList<T>> Sequence<E, T>(this IEnumerable<Result<E, T>> results)
    {
        ArgumentNullException.ThrowIfNull(results);

        var lst = new List<T>();
        foreach (var r in results)
        {
            r.ThrowIfNotInitialized();
            if (!r.IsSuccess)
                return Result<E, IReadOnlyList<T>>.Fail(r.Error);
           
            lst.Add(r.Value);
        }

        return Result<E, IReadOnlyList<T>>.Ok(lst);
    }

    /// <summary>
    /// Applies a function to a sequence and combines the results into one Result
    /// <para>シーケンスに関数を適用してResultにまとめる。</para>
    /// </summary>
    /// <typeparam name="E">Type of error / エラーの型</typeparam>
    /// <typeparam name="T">Type of value / 値の型</typeparam>
    /// <typeparam name="U"></typeparam>
    /// <param name="items"></param>
    /// <param name="selector"></param>
    /// <returns></returns>
    public static Result<E, IReadOnlyList<U>> Traverse<E, T, U>(this IEnumerable<T> items, Func<T, Result<E, U>> selector)
    {
        ArgumentNullException.ThrowIfNull(items);
        ArgumentNullException.ThrowIfNull(selector);

        var lst = new List<U>();
        foreach (var item in items)
        {
            var r = selector(item);
            r.ThrowIfNotInitialized();
            if (!r.IsSuccess)
                return Result<E, IReadOnlyList<U>>.Fail(r.Error);

            lst.Add(r.Value);
        }

        return Result<E, IReadOnlyList<U>>.Ok(lst);
    }
    #endregion

    /// <summary>
    /// Combines two results using a selector function.
    /// <para>2つの Result を関数で組み合わせる。</para>
    /// </summary>
    public static Result<E, U> Combine<E, T, R, U>(this Result<E, T> result, Result<E, R> other, Func<T, R, U> selector)
    {
        result.ThrowIfNotInitialized();
        other.ThrowIfNotInitialized();
        ArgumentNullException.ThrowIfNull(selector);

        if (!result.IsSuccess)
            return Result<E, U>.Fail(result.Error);
        if (!other.IsSuccess)
            return Result<E, U>.Fail(other.Error);

        var val = selector(result.Value, other.Value);
        if (val is null)
            throw new InvalidOperationException("Selector must not return null");

        return Result<E, U>.Ok(val);
    }
}
